name: Validate

on:
  workflow_dispatch:

env:
  LULA_VERSION: 'v0.16.0'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Lula
      run: |
        curl -L -o lula_${{ env.LULA_VERSION }}_Linux_amd64 https://github.com/defenseunicorns/lula/releases/download/${{ env.LULA_VERSION }}/lula_${{ env.LULA_VERSION }}_Linux_amd64
        curl -L -o checksums.txt https://github.com/defenseunicorns/lula/releases/download/${{ env.LULA_VERSION }}/checksums.txt
        sha256sum -c checksums.txt --ignore-missing

        chmod +x lula_${{ env.LULA_VERSION }}_Linux_amd64
        sudo mv lula_${{ env.LULA_VERSION }}_Linux_amd64 /usr/local/bin/lula
        lula version

    - name: Run validations
      run: |
        lula validate -f oscal-superset.yaml